name: Pre Merge Checks

on:
  push:
    branches:
      - master
    paths:
      - "sample/**"
      - "buildSrc/**"
      - "gradle/**"
      - "keyboard-state-events/**"
  pull_request:
    branches:
      - '*'

jobs:
  gradle:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    if: ${{ !contains(github.event.head_commit.message, '[skip ci]') }}
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v1
                
      - name: Cache Gradle Caches
        uses: actions/cache@v2
        with:
          path: ~/.gradle/caches/
          key: cache-gradle-cache     
        
      - name: Cache Gradle Wrapper
        uses: actions/cache@v2
        with:
          path: ~/.gradle/wrapper/
          key: cache-gradle-wrapper

      - name: Run Gradle tasks
        run: ./gradlew build check publishToMavenLocal --continue

      - name: Stop Gradle
        run: ./gradlew --stop
